### ISSUE TITLE
Expired TPIDs can gather and claim rewards while expired.

### ISSUE THREAD

**Issue by edrotthoff** [fioprotocol/fio.contracts#129]
looking at the update tpid and tpid claim for staking and I notice there are no checks for expired addresses used in tpid..

this means that tpids may be able to gather and claim rewards after they are expired and until they are burned.

lets examine this and decide the desired behavior for expired tpids.

**Comment by ericbutz** [comment]
Moved this to a jira story: https://fioprotocol.atlassian.net/browse/BD-2527
