### ISSUE TITLE
regproxy results in faulty record in voters table if account already has a voteproducer record

### ISSUE THREAD

**Issue by prcolaco** [fioprotocol/fio.contracts#29]
if you regproxy on an account that already has a regular voteproducer record in voters table, then the result is that neither the fioaddress nor the addresshash are included in the modified record, as they should if the record would be emplaced.

**Comment by dapixcasey** [comment]
When using the modify method, you only need to supply the data members which are being modified. All other data members inside the entry will stay the same if not included. The action is searching for an entry and your PR is attempting to modify the entry and set it to the same value, which causes unneeded overhead.

**Comment by prcolaco** [comment]
I think you probably didn't see the problem... Please check here: https://fio.bloks.io/#proxies
Look for our proxy "proxy@decentrawise", don't find it there, right? But it should be in line 4...
This is the problem.

**Comment by fiocasey** [comment]
https://github.com/fioprotocol/fio.contracts/pull/30

**Comment by fiocasey** [comment]
PR merged after I was able to duplicate. Thanks for submitting the issue!
